### ISSUE TITLE
Cannot update with two repositories

### ISSUE THREAD

**Issue by sehraf** [hbiyik/agr#1]
I've two repositories added and cannot update:
```
❯ LANG=C python -m agr update
     INFO | Looking up remote: https://github.com/hbiyik/agrrepo.git
     INFO | Looking up remote: https://github.com/sehraf/agrrepo.git
      AGR | Result time: 28.85 seconds
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rock/.local/lib/python3.11/site-packages/agr.py", line 146, in <module>
    main()
  File "/home/rock/.local/lib/python3.11/site-packages/agr.py", line 136, in main
    for line in repo.installpkgs(*update.pkgstoupdate(*ignores), ignorearch=args.ignorearch,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/update.py", line 20, in pkgstoupdate
    for pkgb in repo.allpkgbuilds():
                ^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/cache.py", line 38, in decorated
    retval = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/repo.py", line 76, in allpkgbuilds
    for pkgpath in iterpkgs(premote, branch):
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/repo.py", line 61, in iterpkgs
    git.syncremote(remote, branch)
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/cache.py", line 38, in decorated
    retval = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/git.py", line 56, in syncremote
    cmd.stdout("git", "fetch", "origin", branch, cwd=rpath, env=defs.ENV_GITNOSTDIN)
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/cmd.py", line 31, in stdout
    raise OSError(p.returncode)
OSError: 128
```

Using debug output, I see that is tried to access a repo/packages from the first repo while the second one is checked out. So my uneducated guess is that there is an issue with the order of operations:
```
    INFO | Looking up remote: https://github.com/sehraf/agrrepo.git
    DEBUG | c87e4721b58012b0eb33cc56f724c3ca75f88eea
    DEBUG | Executing: 'rm -rf agrrepo', kwargs: {'cwd': '/home/rock/.agr/gitrepos'}
    DEBUG | Executing: 'git rev-parse HEAD:gitweb-dlagent', kwargs: {'cwd': '/home/rock/.agr/gitrepos/agrrepo'}
    DEBUG | b7adc71003668ed28d30adf6b24f5d11fd496570
    DEBUG | Worker 20 started
    DEBUG | Executing: 'git rev-parse HEAD:libmali-valhall-g610', kwargs: {'cwd': '/home/rock/.agr/gitrepos/agrrepo'}
    DEBUG | Worker 17 ended
    DEBUG | Worker 16 ended
    DEBUG | 22c90d07ef7b6f3c2fbd64b71d9ad4ff9f18174f
    DEBUG | e706b97991add4ee23273182195db1c0c33e14ec
    DEBUG | Worker 18 ended
    DEBUG | e10b3d5d9e13b5835db53d6259bd2e2c100f5992
    DEBUG | Worker 19 ended
    DEBUG | Worker 20 ended
    DEBUG | Executing: 'git clone -b main https://github.com/sehraf/agrrepo.git', kwargs: {'cwd': '/home/rock/.agr/gitrepos', 'env': {...}}
    DEBUG | Cloning into 'agrrepo'...
    DEBUG | Executing: 'git submodule update --init --recursive', kwargs: {'cwd': '/home/rock/.agr/gitrepos/agrrepo', 'env': {...}}
    DEBUG | Executing: 'git submodule foreach --recursive git fetch', kwargs: {'cwd': '/home/rock/.agr/gitrepos/agrrepo', 'env': {...}}
    DEBUG | Executing: 'git submodule foreach --recursive git clean -d -x -f -f', kwargs: {'cwd': '/home/rock/.agr/gitrepos/agrrepo', 'env': {...}}
    DEBUG | Executing: 'git submodule update --recursive --remote --force', kwargs: {'cwd': '/home/rock/.agr/gitrepos/agrrepo', 'env': {...}}
    DEBUG | Worker 21 started
    DEBUG | Executing: 'git rev-parse HEAD:mangohud', kwargs: {'cwd': '/home/rock/.agr/gitrepos/agrrepo'}
    DEBUG | b6e6efb50265af5ba01916e2b7d3f2fdb234f704
    DEBUG | Worker 21 ended
      AGR | Result time: 18.85 seconds
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rock/.local/lib/python3.11/site-packages/agr.py", line 146, in <module>
    main()
  File "/home/rock/.local/lib/python3.11/site-packages/agr.py", line 136, in main
    for line in repo.installpkgs(*update.pkgstoupdate(*ignores), ignorearch=args.ignorearch,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/update.py", line 34, in pkgstoupdate
    pkgb.sync()
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/cache.py", line 38, in decorated
    retval = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/pkgbuild.py", line 130, in sync
    git.syncworking(self.remote, self.pkgfullpath, self.workpath)
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/cache.py", line 38, in decorated
    retval = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rock/.local/lib/python3.11/site-packages/libagr/git.py", line 72, in syncworking
    for fname in os.listdir(pkgfullpath):
                 ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/rock/.agr/gitrepos/agrrepo/gl4es-git'
```
In the 3rd line all repos are deleted and the second one is checked out. At the end it tries to access `gl4es-git` which is part of the first repo.

**Comment by hbiyik** [comment]
The problem was both repos were using agrrepo as repo name, and i was using the remote reponame as foldername, so they were colliding with each other.

I have refactored the logic a lot and should be fixed with latest.

Can you `agr update --agr` and check if it is fixed and hopefully did not cause another issue.

Note: i did not bump the version yet, you will still have the same version after update, but it will have the latest commit.

**Comment by sehraf** [comment]
works like a charm, thanks!
