### ISSUE TITLE
Agr Error " Please install git packages to use container native:

### ISSUE THREAD

**Issue by nrpetonr** [hbiyik/agr#3]
hi, i'm trying to run it acc. to instructions, but it fails with error as shown below. tried to google for the answer, but could not find any. thx for looking into this.

OS: Arch Linux ARM aarch64 
Host: Orange Pi 5 Plus 
Kernel: 6.1.75-rockchip-g5c43412639fd-dirty

```
[archlinux@archlinux` ~]$ agr
     INFO | Running in container native
    ERROR | Please install git packages to use container native
      AGR | Result time: 1.23 seconds
Traceback (most recent call last):
  File "/usr/local/bin/agr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/agr.py", line 34, in main
    c = cont()
        ^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 42, in __init__
    self.checkpkgs(self.installed)
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 311, in checkpkgs
    raise(RuntimeError(msg))
RuntimeError: Please install git packages to use container native
```

**Comment by hbiyik** [comment]
sudo pacman -Sy git

as the message says :)
