### ISSUE TITLE
firefox-mpp 132.0.1-1  -  ERROR: One or more PGP signatures could not be verified!

### ISSUE THREAD

**Issue by nrpetonr** [hbiyik/agr#4]
OS: Arch Linux ARM aarch64
Host: Orange Pi 5 Plus
Kernel: 6.1.75-rockchip-g5c43412639fd-dirty

```
==> Making package: firefox-mpp 132.0.1-1 (Mon Nov 11 07:20:33 2024)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found firefox-132.0.1.source.tar.xz
  -> Found firefox-132.0.1.source.tar.xz.asc
  -> Found firefox-symbolic.svg
  -> Found firefox.desktop
  -> Found org.mozilla.firefox.metainfo.xml
  -> Found mpp.patch
==> Validating source files with sha256sums...
    firefox-132.0.1.source.tar.xz ... Passed
    firefox-132.0.1.source.tar.xz.asc ... Skipped
    firefox-symbolic.svg ... Passed
    firefox.desktop ... Passed
    org.mozilla.firefox.metainfo.xml ... Passed
    mpp.patch ... Skipped
==> Validating source files with b2sums...
    firefox-132.0.1.source.tar.xz ... Passed
    firefox-132.0.1.source.tar.xz.asc ... Skipped
    firefox-symbolic.svg ... Passed
    firefox.desktop ... Passed
    org.mozilla.firefox.metainfo.xml ... Passed
    mpp.patch ... Skipped
==> Verifying source file signatures with gpg...
    firefox-132.0.1.source.tar.xz ... FAILED (unknown public key E36D3B13F3D93274)
==> ERROR: One or more PGP signatures could not be verified!
      AGR | Result time: 712.76 seconds
Traceback (most recent call last):
  File "/usr/local/bin/agr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/agr.py", line 35, in main
    if(not c.exec_commands(report, args)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 251, in exec_commands
    getattr(self, f"cmd_{cmd}")(report, **kwargs)
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 157, in cmd_install
    packages = self.cmd_build(report, pkgname, repo, no_repo, agrfirst, skipinteg, skippgpcheck, skipchecksum, noconfirm, ignorearch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 152, in cmd_build
    return agrrepo.buildpkgs(self, packages, no_packages, repo, no_repo, agrfirst, skippgpcheck, skipchecksum, skipinteg, noconfirm, ignorearch=ignorearch, force=force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/repo.py", line 199, in buildpkgs
    if base_package.pkgbuild.build(force, skippgpcheck, skipchecksum, skipinteg, noconfirm, ignorearch) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/pkgbuild.py", line 368, in build
    retval = self.container.run_interactive("makepkg", "-s", *args, cwd=self.pkgfullpath, env=self.env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 345, in run_interactive
    return agrcmd.run_interactive(*cmd, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/cmd.py", line 15, in run_interactive
    raise OSError(p.returncode)

```

**Comment by hbiyik** [comment]
give the option `--skippgpcheck`.

**Comment by nrpetonr** [comment]
thanks for prompt supports. it fixed that error, unfortunately another one popped up when trying to get firefox-mpp. sorry to bother...

```
==> ERROR: A failure occurred in prepare().
    Aborting...
      AGR | Result time: 474.55 seconds
Traceback (most recent call last):
  File "/usr/local/bin/agr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/agr.py", line 35, in main
    if(not c.exec_commands(report, args)):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 251, in exec_commands
    getattr(self, f"cmd_{cmd}")(report, **kwargs)
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 157, in cmd_install
    packages = self.cmd_build(report, pkgname, repo, no_repo, agrfirst, skipinteg, skippgpcheck, skipchecksum, noconfirm, ignorearch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 152, in cmd_build
    return agrrepo.buildpkgs(self, packages, no_packages, repo, no_repo, agrfirst, skippgpcheck, skipchecksum, skipinteg, noconfirm, ignorearch=ignorearch, force=force)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/repo.py", line 199, in buildpkgs
    if base_package.pkgbuild.build(force, skippgpcheck, skipchecksum, skipinteg, noconfirm, ignorearch) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/pkgbuild.py", line 368, in build
    retval = self.container.run_interactive("makepkg", "-s", *args, cwd=self.pkgfullpath, env=self.env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/container/native.py", line 345, in run_interactive
    return agrcmd.run_interactive(*cmd, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archlinux/.local/lib/python3.12/site-packages/libagr/cmd.py", line 15, in run_interactive
    raise OSError(p.returncode)
OSError: 4
```

**Comment by hbiyik** [comment]
this package is using archlinux arm package firefox. https://github.com/archlinuxarm/PKGBUILDs/tree/master/extra/firefox

seems like it requires a clean build, therefore you can also do a clean build with `-f`

`agr build -f firefox-mpp --noconfirm --skippgpcheck`

**Comment by nrpetonr** [comment]
installed , working like a charm. thanks a lot.
i am gonna have to look into widevine which  does not work when using available scripts for fixing…

**Comment by hbiyik** [comment]
Enjoy
